# server environment configuration
uvicorn:
  host: 0.0.0.0
  port: 8000
  log_level: info
  reload: false
db_connection:
  postgres_user: ${POSTGRES_USER}
  postgres_password: ${POSTGRES_PASSWORD}
  postgres_server: ${POSTGRES_SERVER}
  postgres_database: ${POSGRES_DATABASE}
#  postgres_user: taybur
#  postgres_password: ece1109043
#  postgres_server: 192.168.0.102
#  postgres_database: simple-app
api_config:
  title: Simple FastAPI Server
  description: API Documentation for Simple FastAPI Server
  version: v1
  docs_url: /docs
