version: "3.9"

services:
  database:
    image: postgres:14.2
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${PostgresUser}
      - POSTGRES_PASSWORD=${PostgresPassword}
      - POSTGRES_SERVER=${PostgresServer}
      - POSTGRES_DB=${PostgresDatabase}
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - database
    ports:
      - "8000:8000"